// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Александр",
            "url": "https://vk.com/a13handro"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/login": {
            "post": {
                "tags": [
                    "Authorization"
                ],
                "summary": "Авторизация",
                "responses": {}
            }
        },
        "/api/auth/refresh-token": {
            "post": {
                "description": "метод вызывается автоматически из функции-оболочки (AuthMiddleware) при невалидном Accesstoken",
                "tags": [
                    "RefreshToken"
                ],
                "summary": "Обновление токена",
                "responses": {}
            }
        },
        "/api/auth/register": {
            "post": {
                "tags": [
                    "Authorization"
                ],
                "summary": "Регистрация",
                "responses": {}
            }
        },
        "/api/posts": {
            "get": {
                "description": "Требует аутентификации.",
                "tags": [
                    "Posts"
                ],
                "summary": "Просмотр постов",
                "responses": {}
            },
            "post": {
                "description": "Требует аутентификации(Роль Автор).",
                "tags": [
                    "Posts"
                ],
                "summary": "Создание поста",
                "responses": {}
            }
        },
        "/api/posts/{postId}": {
            "put": {
                "description": "Требует аутентификации(Роль Автор).",
                "tags": [
                    "Posts"
                ],
                "summary": "Редактирование поста",
                "responses": {}
            }
        },
        "/api/posts/{postId}/images": {
            "post": {
                "description": "Требует аутентификации(Роль Автор).",
                "tags": [
                    "Image"
                ],
                "summary": "Добавление картинки к посту",
                "responses": {}
            }
        },
        "/api/posts/{postId}/images/{imageId}": {
            "delete": {
                "description": "Требует аутентификации(Роль Автор).",
                "tags": [
                    "Image"
                ],
                "summary": "Удаление картинки из поста",
                "responses": {}
            }
        },
        "/api/posts/{postId}/status": {
            "patch": {
                "description": "Требует аутентификации(Роль Автор).",
                "tags": [
                    "Posts"
                ],
                "summary": "Публикация поста",
                "responses": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "API на Go со Swagger",
	Description:      "Сайт",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
