// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Александр",
            "url": "https://vk.com/a13handro"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api": {
            "get": {
                "tags": [
                    "Master"
                ],
                "summary": "Главная страница",
                "responses": {}
            }
        },
        "/api/auth/log": {
            "post": {
                "tags": [
                    "Authorization"
                ],
                "summary": "Метод обработки авторизации",
                "responses": {}
            }
        },
        "/api/auth/login": {
            "get": {
                "tags": [
                    "Authorization"
                ],
                "summary": "Страница авторизации",
                "responses": {}
            }
        },
        "/api/auth/reg": {
            "post": {
                "tags": [
                    "Registration"
                ],
                "summary": "Метод обработки регистрации",
                "responses": {}
            }
        },
        "/api/auth/register": {
            "get": {
                "tags": [
                    "Registration"
                ],
                "summary": "Страница регистрации",
                "responses": {}
            }
        },
        "/api/pos": {
            "post": {
                "description": "Требует аутентификации. Функция для создания и изменения поста. Сложная логика с картинками: при создании нужно выбрать будет картинка или нет, а при изменении можно не менять.",
                "tags": [
                    "Posts"
                ],
                "summary": "Обработка создания поста или изменения поста",
                "responses": {}
            }
        },
        "/api/posts": {
            "get": {
                "description": "Требует аутентификации. Проверяет роль. Если роль читателя, то выдает сообщение и перенаправляет на главную страницу.",
                "tags": [
                    "Posts"
                ],
                "summary": "Страница создания поста",
                "responses": {}
            }
        },
        "/delete_post/{id}": {
            "get": {
                "description": "Требует аутентификации.",
                "tags": [
                    "Posts"
                ],
                "summary": "Удаление поста",
                "responses": {}
            }
        },
        "/post/{id}": {
            "get": {
                "description": "Требует аутентификации.",
                "tags": [
                    "Posts"
                ],
                "summary": "Страница редактирования поста",
                "responses": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "API на Go со Swagger",
	Description:      "Сайт",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
