basePath: /api/v1
host: localhost:8080
info:
  contact:
    name: Александр
    url: https://vk.com/a13handro
  description: Сайт
  title: API на Go со Swagger
  version: "1.0"
paths:
  /api/auth/login:
    post:
      responses: {}
      summary: Авторизация
      tags:
      - Authorization
  /api/auth/refresh-token:
    post:
      description: метод вызывается автоматически из функции-оболочки (AuthMiddleware)
        при невалидном Accesstoken
      responses: {}
      summary: Обновление токена
      tags:
      - Authorization
  /api/auth/register:
    post:
      responses: {}
      summary: Регистрация
      tags:
      - Authorization
  /api/posts:
    get:
      description: Требует аутентификации.
      responses: {}
      summary: Просмотр постов
      tags:
      - Viewing
    post:
      description: Требует аутентификации(Роль Автор).
      responses: {}
      summary: Создание поста
      tags:
      - Posts
  /api/posts/{postId}:
    put:
      description: Требует аутентификации(Роль Автор).
      responses: {}
      summary: Редактирование поста
      tags:
      - Edit
  /api/posts/{postId}/images:
    post:
      description: Требует аутентификации(Роль Автор).
      responses: {}
      summary: Добавление картинки к посту
      tags:
      - Images
  /api/posts/{postId}/images/{imageId}:
    delete:
      description: Требует аутентификации(Роль Автор).
      responses: {}
      summary: Удаление картинки из поста
      tags:
      - Delete
  /api/posts/{postId}/status:
    patch:
      description: Требует аутентификации(Роль Автор).
      responses: {}
      summary: Публикация поста
      tags:
      - Publish
swagger: "2.0"
